name: Sync Ascend Image To Shenzhen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 登录国内阿里云深圳仓库
      run: |
        # 使用你真正的深圳个人实例域名进行登录
        docker login --username=${{ secrets.ALI_USER2 }} --password=${{ secrets.ALI_PASSWORD }} crpi-bf0yte5512ys4qfu.cn-shenzhen.personal.cr.aliyuncs.com

    - name: 海外机房全速拉取并精准推送
      run: |
        # 1. 微软海外机房秒级拉取官方原版 quay.io 镜像
        docker pull quay.io/ascend/vllm-ascend:v0.18.0-a3-arm64
        
        # 2. 修改标签（请把下面的“访问凭证”换成你自己在阿里云建立的【命名空间】名字）
        docker tag quay.io/ascend/vllm-ascend:v0.18.0-a3 crpi-bf0yte5512ys4qfu.cn-shenzhen.personal.cr.aliyuncs.com/vllm-ascend-sync/vllm-ascend:v0.18.0-a3
        
        # 3. 顺着大带宽网线直接推回国内深圳仓
        docker push crpi-bf0yte5512ys4qfu.cn-shenzhen.personal.cr.aliyuncs.com/vllm-ascend-sync/vllm-ascend:v0.18.0-a3
